title: "Valérie Plusquellec"
logo: /img/vp.jpeg

description: >
  -------- Me contacter --------
  vplusquellec.data@gmail.com
  ---------- LinkedIn ----------
  www.linkedin.com/in/valerie-plusquellec/

show_downloads: false
theme: jekyll-theme-minimal
lang: fr

github:
  is_project_page: false
