title: "Valérie Plusquellec"
logo: /img/vp.jpeg

description: >
  -------Data Analyst - Data Scientist-------
  vplusquellec.data@gmail.com
  www.linkedin.com/in/valerie-plusquellec/

show_downloads: false
theme: jekyll-theme-minimal
lang: fr

github:
  is_project_page: false
